path_to_alteryx: /path/to/your/workflow.yxmd
log_to:
  table: log_table
  connection_string: your_connection_string
admins:
  - admin1
  - admin2
mode: TESTING
flow_execution:
  error_handling_settings:
    on_error: "warn"
  timeout_settings:
    on_timeout: raise
    timeout_duration: 60


