name: diff-action

# Run on all push events
on:
  push:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed to checkout all branches for this Action to work

      # Check the PR diff using the current branch and the base branch of the PR
      - uses: GrantBirki/git-diff-action@v2.1.1
        id: git-diff-action
        with:
          json_diff_file_output: diff.json
          raw_diff_file_output: diff.txt
          file_output_only: "true"

      # Create a GitHub Gist with the full Git diff
      - name: Create Gist
        id: create-gist
        run: |
          echo "Full Git Diff:" > gist_body.txt
          cat ${{ steps.git-diff-action.outputs.raw-diff-path }} >> gist_body.txt
          gh gist create --public gist_body.txt

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create an issue with a link to the Gist
      - name: Create Issue
        run: |
          echo "Here is the Git diff: [Full Diff](${{ steps.create-gist.outputs.html_url }})" > issue_body.txt
          echo "The diff has been shared as a GitHub Gist for brevity." >> issue_body.txt
          gh issue create --title "GitHub Action Notification" --body-file issue_body.txt

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
